dbt_project:
  outputs:
    dev:
      database: dbt_project
      driver: ODBC Driver 18 for SQL Server
      encrypt: false
      port: 1433
      schema: dbt
      server: JM-INA435R859
      type: sqlserver
      windows_login: true
  target: dev
major_project_dbt:
  outputs:
    dev:
      account: gn96813.central-india.azure
      database: MAJOR_PROJECT_DB
      password: Kumaresh@snowflake007
      role: ACCOUNTADMIN
      schema: DBO
      threads: 1
      type: snowflake
      user: Kumaresharul007
      warehouse: COMPUTE_WH
  target: dev
